ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'PENDING_PAYMENT';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'PURCHASING';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'SHIPPING';
ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'READY_FOR_DELIVERY';
ALTER TABLE "WebsiteOrderRequest" ADD COLUMN IF NOT EXISTS "quotedPrice" DECIMAL(18,3);
ALTER TABLE "WebsiteOrderRequest" ADD COLUMN IF NOT EXISTS "paymentRequested" BOOLEAN NOT NULL DEFAULT false;
